version: 2

sources:
  - name: bronze
    schema: main
    tables:
      - name: bronze_listings
        columns:
          - name: id
            tests:
              - not_null
              - unique
      - name: bronze_hosts
        columns:
          - name: id
            tests:
              - not_null
              - unique
      - name: bronze_reviews
      - name: bronze_full_moon